version: '3.8'

services:
  bot:
    build: .
    container_name: discord_bot
    environment:
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
    volumes:
      - .:/app
    ports:
      - "8000:80"
